# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

"alacritty" = "ï„ "
"github" = "ï„“"
"robo3t" = "ïŠ™"
"rdm" = "î™­"
"code" = "ï„¡"
"google" = "ï† "
"jenkins" = "ï¶"
"private browsing" = "ïˆ›"
"firefox" = "ï‰©"
"chrome" = "ï‰¨"
"file manager" = "ï»"
"nvim" = "ï„ "
"gthumb" = "ï€¾"
"menu" = "ï¡œ"
"calculator" = "ï—«"
"transmission" = "ï€™"
"mpv" = "ïœª"
"music" = "ï€"
"disk usage" = "ïŸ‰"
"intellij" = "ï„¡"
"settings" = "ï€“"
"steam" = "ï†¶ "
[other]
"fallback_icon" = "ğŸ—–"
deduplicate_icons = false
